export const DEF = {
  // EN_: ,
  // EN - POPOVER LIST //
  EN_RECEIPT: "Receipt / Deposit",
  EN_REFUND: "Debit / Withdraw",
  EN_TICKET: "Ticket",
  EN_FINANCIAL: "Financial Management",
  EN_SERVICE: "Service",
  EN_STATMENT_OF_ACCOUNT: "Statement of Account",
  EN_DISCONNECT: "Disconnect",
  EN_PING: "Ping",
  EN_CLEAR_MAC: "Clear MAC",
  EN_CHANGE_SERVICE: "Change Service",
  EN_RECHARGE: "Recharge",
  EN_END_SESSION: "End Session",
  EN_ADD_TO_ARCHIVE: "Add to Archive List",
  EN_EXTRA_GIGA: "Extra Giga",
  EN_CONSUMPTION: "Consumption",
  EN_DIRECTIONS: "Directions",
  EN_DETAILS: "Details",
  EN_VISIT: "Visit",
  EN_REMINDER: "Remind Me Later",
  EN_SHOW_NEIGHBORS: "Show Neighbors",
  EN_WHATSAPP: "WhatsApp",
  EN_INFECT: "Infect",
  EN_SERVICES: "Services",

  // AR - POPOVER LIST //
  AR_RECEIPT: "إيداع",
  AR_REFUND: "صرف",
  AR_TICKET: "تذكرة مساعدة",
  AR_FINANCIAL: "المحاسبة والفواتير",
  AR_SERVICE: "الخدمة",
  AR_STATMENT_OF_ACCOUNT: "كشف حساب",
  AR_DISCONNECT: "Disconnect",
  AR_PING: "Ping",
  AR_CLEAR_MAC: "Clear MAC",
  AR_CHANGE_SERVICE: "تغيير الخدمة",
  AR_RECHARGE: "اعادة شحن",
  AR_END_SESSION: "End Session",
  AR_ADD_TO_ARCHIVE: "Add to Archive List",
  AR_EXTRA_GIGA: "Extra Giga",
  AR_CONSUMPTION: "قراءة العداد",
  AR_DIRECTIONS: "الاتجاه لبيت المشترك",
  AR_DETAILS: "معلومات المشترك",
  AR_VISIT: "زيارة",
  AR_REMINDER: "ذكرني لاحقاً",
  AR_SHOW_NEIGHBORS: "الجيران",
  AR_WHATSAPP: "الواتساب",
  AR_INFECT: "مصاب",
  AR_SERVICES: "الخدمات",

  // EN - DETAILS + MANAGE//
  EN_NAME: "Name",
  EN_USERNAME: "Username",
  EN_PASSWORD: "Password",
  EN_LOGIG_PASSWORD: "App Password",
  EN_NODE: "Node",
  EN_ADDRESS: "Address",
  EN_MOBILE: "Mobile",
  EN_EMAIL: "Email",
  EN_PHONE: "Phone",
  EN_NATIONALITY: "Nationality",
  EN_WHATSAPP_MOBILE: "WhatsApp Mobile",
  EN_SERVICE_TYPE: "Service Type",
  EN_LAST_LOGIN: "Last Login",
  EN_LAST_LOGOUT: "Last Logout",
  EN_MAC_ADDRESS: "MAC Address",
  EN_ROUTER_MODEL: "Router Model",
  EN_CATEGORY: "Category",
  EN_COLLECTOR: "Collector",
  EN_FRAMED_IP: "Framed IP",
  EN_EXPIRY_DATE: "Expiry Date",
  EN_BALANCE: "Balance",
  EN_SPEED: "Speed",
  EN_AUTO_RECHARGE: "Auto Recharge",
  EN_FALLBACK: "Fallback",
  EN_DISCOUNT: "Discount",
  EN_DISCOUNT_DESC: "Discount Desc.",
  EN_ACCOUNT_NAME: "Account Name",

  // AR - DETAILS + MANAGE//
  AR_NAME: "الاسم",
  AR_USERNAME: "اسم المستخدم",
  AR_PASSWORD: "الرمز السري",
  AR_LOGIG_PASSWORD: "الرمز السري للبرنامج",
  AR_NODE: "المبنى",
  AR_ADDRESS: "العنوان",
  AR_MOBILE: "الجوال",
  AR_EMAIL: "البريد الالكتروني",
  AR_PHONE: "الهاتف",
  AR_NATIONALITY: "الجنسية",
  AR_WHATSAPP_MOBILE: "رقم الواتساب",
  AR_SERVICE_TYPE: "نوعية الخدمة",
  AR_LAST_LOGIN: "آخر دخول",
  AR_LAST_LOGOUT: "آخر خروج",
  AR_MAC_ADDRESS: "MAC Address",
  AR_ROUTER_MODEL: "Router Model",
  AR_CATEGORY: "التصنيف",
  AR_COLLECTOR: "اسم الجابي",
  AR_FRAMED_IP: "Framed IP",
  AR_EXPIRY_DATE: "تاريخ الانتهاء",
  AR_BALANCE: "الرصيد",
  AR_SPEED: "السرعة",
  AR_AUTO_RECHARGE: "اعادة تفعيل تلقائية",
  AR_FALLBACK: "Fallback",
  AR_DISCOUNT: "الخصم",
  AR_DISCOUNT_DESC: "تفاصيل الخصم",
  AR_ACCOUNT_NAME: "اسم الحساب",

  // EN - MAIN VIEW + MENU //
  EN_ONLINE: "Online",
  EN_OFFLINE: "Offline",
  EN_ENABLE: "Enable",
  EN_ENABLED: "Enabled",
  EN_DISABLE: "Disable",
  EN_DISABLED: "Disabled",
  EN_LOCKED: "LOCKED",
  EN_TERMINATE: "Terminate",
  EN_EDIT: "Edit",
  EN_SUBSCRIBER_LIST: "Subscriber List",
  EN_MY_SERVICES: "My Services",
  EN_VIEW_BY_CATEGORY: "View By Category",
  EN_TOTAL: "Total",
  EN_INFECTED: "Infected",
  EN_ARCHIVED: "Archived",
  EN_ACTIVE: "Active",
  EN_SUSPENDED: "Suspended",
  EN_EXPIRED: "Expired",
  EN_REGIONS: "Regions",
  EN_GLOBAL_SEARCH: "Global Search",
  EN_ROUTE: "Route",
  EN_OVER_CREDIT_LIMIT: "Over Credit Limit",
  EN_NEED_RECHAREG: "Need Recharge",
  EN_NO_REGISTERED_DATE: "No registered date",
  EN_SHARE_LOCATION: "Share Location",
  EN_COLLECTOR_SUMMARY: "Collector Summary",
  EN_MY_DEALERS: "My Dealers",
  
  // AR - MENU //
  AR_SHARE_LOCATION: "مشاركة الموقع",
  AR_MY_SERVICES: "خدماتي",
  AR_COLLECTOR_SUMMARY: "ملخص الجباية",
  AR_MY_DEALERS: "الموزعين",
  AR_VIEW_BY_CATEGORY: "عرض التصنيفات",

  // EN - LOGIN //
  EN_CHOOSE_ACCOUNT:  "Choose account",
  EN_ADD_ACCOUNT:  "Add Account",
  EN_VERSION: "v",

  // AR - LOGIN //
  AR_CHOOSE_ACCOUNT:  "اختر حساباً",
  AR_ADD_ACCOUNT:  "أضف حساباً",
  AR_VERSION: "الإصدار",

  // EN - Collector View //
  // EN_GLOBAL_SEARCH: "Global Search",
  EN_REMINDED_USERS: "Reminded Users",

  // AR - Collector View //
  AR_GLOBAL_SEARCH: "بحث",
  AR_REMINDED_USERS: "المشتركون المؤجلون",

  // EN - Main View //
  EN_SUB_LIST_TITLE: "Subscriber List",

  // AR - Main View //
  AR_SUB_LIST_TITLE: "قائمة المشتركين",


  // EN - Sub Counters //
  EN_ALL : "All",
  EN_GRACE_PERIOD :"Grace Period",

  // AR - Sub Counters //
  AR_ALL : "الجميع",
  AR_ONLINE: "أونلاين",
  AR_OFFLINE: "أوفلاين",
  AR_ENABLE: "مفعّل",
  AR_ENABLED: "مفعلين",
  AR_DISABLE: "معطّل",
  AR_DISABLED: "معطلين",
  AR_EXPIRED: "منتهية",
  AR_ARCHIVED: "مؤرشف",
  AR_INFECTED: "مصاب",
  AR_TERMINATE: "انهاء",
  AR_GRACE_PERIOD: "فترة السماح",

  // EN - Server Popup //
  EN_SERVERS_LIST: "Servers List",
  EN_UPDATE_ACCOUNT: "Update Account",
  EN_DELETE_ACCOUNT: "Delete Account",

  // AR - Server Popup //
  AR_SERVERS_LIST: "قائمة الخوادم",
  AR_UPDATE_ACCOUNT: "تحديث الحساب",
  AR_DELETE_ACCOUNT: "حذف الحساب",


  // EN - Add / Manage Sub //
  EN_ADD_SUBSCRIBER_TITLE: 'Add Subscriber',
  EN_EDIT_SUBSCRIBER_TITLE: 'Edit Subscriber',
  EN_ADDITION_TITLE: 'Addition',
  EN_ADDITION_DESC_TITLE: 'Addition Desc',
  EN_PARENT_ACCOUNT_TITLE: 'Parent Account',
  EN_PAYMENT_METHOD_TITLE: 'Payment Method',
  // EN: '',
  
  // AR - Add / Manage Sub //
  AR_ADD_SUBSCRIBER_TITLE: 'إضافة مستخدم',
  AR_EDIT_SUBSCRIBER_TITLE: 'تعديل مستخدم',
  AR_ADDITION_TITLE: 'الإضافة',
  AR_ADDITION_DESC_TITLE: 'تفاصيل الإضافة',
  AR_PARENT_ACCOUNT_TITLE: 'الحساب الأصلي',
  AR_PAYMENT_METHOD_TITLE: 'طريقة الدفع',

  // EN - Financial //
  EN_DBT_ACCOUNT: 'Dbt. Account',
  EN_CRT_ACCOUNT: 'Crt. Account',
  EN_FROM: 'From',
  EN_TO: 'To',
  EN_CURRENCY: 'Currency',
  EN_CURRENT_BALANCE: 'Current Balance',
  EN_AMOUNT: 'Amount',
  EN_DESCRIPTION: 'Description',
  EN_SEND: 'Send',
  EN_PRINT: 'Print',
  EN_PRINT_LAST_TRANSACTION: 'Print Last Transaction',

  // AR - Financial //
  AR_DBT_ACCOUNT: 'حساب الدائن',
  AR_CRT_ACCOUNT: 'حساب المدين',
  AR_FROM: 'من',
  AR_TO: 'الى',
  AR_CURRENCY: 'العملة',
  AR_CURRENT_BALANCE: 'الرصيد الحالي',
  AR_AMOUNT: 'المبلغ',
  AR_DESCRIPTION: 'التفاصيل',
  AR_SEND: 'إرسال',
  AR_PRINT: 'طباعة',
  AR_PRINT_LAST_TRANSACTION: 'طباعة آخر ايصال',

  // EN //
  EN_REQUIRED: "Required",
  EN_OPTIONAL: "Optional",

  // AR //
  AR_REQUIRED: "حقل مطلوب",
  AR_OPTIONAL: "حقل اختياري",


  // EN - Options Popup //
  EN_REASONS : "Reasons",
  EN_CLOSE_TICKET : "Close Ticket",
  EN_DATE_TO_REMIND : "Date to Remind",
  EN_PICK_DATE : "Pick a date",
  EN_ACTION_CHANGE_SERVICE : "Change Service",
  EN_ACTION_TERMINATE : "Terminate",
  EN_ACTION_DISABLE : "Disable",
  EN_ACTION_CLOSE_TICKET : "Tasks List",
  EN_ACTION_REMIND_LATER : "Remind me later",

  // AR - Options Popup //
  AR_REASONS : "أسباب",
  AR_CLOSE_TICKET : "إغلاق التذكرة",
  AR_DATE_TO_REMIND : "تاريخ التذكير",
  AR_PICK_DATE : "اختر يوماً",
  AR_ACTION_CHANGE_SERVICE : "تغيير الخدمة",
  AR_ACTION_TERMINATE : "Terminate",
  AR_ACTION_DISABLE : "Disable",
  AR_ACTION_CLOSE_TICKET : "إغلاق التذكرة",
  AR_ACTION_REMIND_LATER : "ذكرني لاحقاً",

  // EN - Visit //
  EN_TYPE: "Type",
  EN_REGISTER_VISIT: "Register a visit",
  
  // AR - Visit //
  AR_TYPE: "النوع",
  AR_REGISTER_VISIT: "تسجيل زيارة",

  // EN - Statement of Account //
  EN_DATE_TIME: "Date / Time",
  EN_DEBT: "Debt",
  EN_CREDIT: "Credit",
  EN_TOTLA_BALANCE: "Total Balance",
  EN_TOTAL_DEBT: "Total Debt",
  EN_TOTAL_CREDIT: "Total Credit",
  EN_OLD_BALANCE: "Old Balance",

  // AR - Statement of Account //
  AR_DATE_TIME: "التوقيت",
  AR_DEBT: "الدين",
  AR_CREDIT: "المستحقات",
  AR_TOTLA_BALANCE: "الاجمالي",
  AR_TOTAL_DEBT: "اجمالي الدين",
  AR_TOTAL_CREDIT: "اجمالي المستحقات",
  AR_OLD_BALANCE: "الاجمالي القديم",


  // EN - Readings //
  EN_READINGS: "Readings",
  EN_SCAN_BARCODE: "Scan Barcode",
  EN_GET_DATA: "Get Data",
  EN_SEND_READING: "Send Reading",
  EN_LAST_READING: "Last Reading",
  EN_LAST_READING_DATE: "Last Reading Date",
  EN_CURRENT_READING: "Current Reading",
  EN_BARCODE_INPUT_PLACEHOLDER: "Or type the code here.",
  EN_NO_SYNCED_DATA: "Sync your data from the menu first.",

  // AR - Readings //
  AR_READINGS: "القراءات",
  AR_SCAN_BARCODE: "مسح الباركود",
  AR_GET_DATA: "معلومات المشترك",
  AR_SEND_READING: "ارسل القراءة",
  AR_LAST_READING: "أخر قراءة",
  AR_LAST_READING_DATE: "تاريخ آخر قراءة",
  AR_CURRENT_READING: "القرآءة الحالية",
  AR_BARCODE_INPUT_PLACEHOLDER: "أو أدخل الباركود هنا",
  AR_NO_SYNCED_DATA: "زامن بياناتك أولاًُ من القائمة الجانبية.",

  // EN - Collector Summary //
  EN_COLLECTOR_SUMMARY_PAGE_TITLE: "Collector Summary",
  EN_COLLECTED: "Collected",
  EN_ENTRIES: "Entries",
  EN_VISITS: "Visits",
  EN_TOTAL_COLLECTED: "Total Collected",
  EN_TOTAL_ENTRIES: "Total Entries",
  EN_TOTAL_VISITS: "Total Visits",

  // AR - Collector Summary //
  AR_COLLECTOR_SUMMARY_PAGE_TITLE: "ملخص الجباية",
  AR_COLLECTED: "المجبي",
  AR_ENTRIES: "المدخلات",
  AR_VISITS: "الزيارات",
  AR_TOTAL_COLLECTED: "اجمالي المجبي",
  AR_TOTAL_ENTRIES: "اجمالي المدخلات",
  AR_TOTAL_VISITS: "اجمالي الزيارات",

  // EN - Invoice //
  EN_NEXT: "Next",
  EN_PREV: "Previous",
  EN_INFO: "Info.",
  EN_INFO_SUB: "General Info.",
  EN_INVOICE_DETAILS: "Details",
  EN_INVOICE_DETAILS_SUB: "Item List",
  EN_TOTALS: "Totals",
  EN_TOTALS_SUB: "Total Cost",
  EN_ACCOUNT: "Account",
  EN_REFERENCE: "Reference",
  EN_AGENT_NAME: "Agent Name",
  EN_DATE: "Date",
  EN_STORE: "Store",
  EN_BARCODE: "Barcode",
  EN_MATERIAL: "Material",
  EN_UNIT: "Unit",
  EN_UNIT_PRICE: "Unit price",
  EN_QUANTITY: "Quantity",
  EN_ITEM_DISC: "Item disc.",
  EN_ITEM_ADD: "Item add.",
  EN_QUANTITY_PRICE: "Quantity price",
  EN_ADD: "Add",
  EN_DELETE: "Delete",
  EN_ADD_ITEM: "Add Item",
  EN_INVOICE_DISC: "Invoice Disc.",
  EN_INVOICE_ADD: "Invoice Add.",
  EN_SUBTOTAL: "Subtotal",
  EN_SUBMIT: "Submit",
  EN_DISC_VALUE: "Disc. value",
  EN_DISC_PERCENT: "Disc. percent",
  EN_ADD_VALUE: "Add. value",
  EN_ADD_PERCENT: "Add. percent",
  EN_TRANSFER: "Transfer",
  EN_PRAINT: "Print",

  // AR - Invoice //
  AR_EDIT: "تعديل",
  AR_LOCKED: "مقفل",
  AR_TOTAL: "المجموع",
  AR_NEXT: "التالي",
  AR_PREV: "السابق",
  AR_INFO: "معلومات",
  AR_INFO_SUB: "معلومات عامة",
  AR_INVOICE_DETAILS: "تفاصيل",
  AR_INVOICE_DETAILS_SUB: "تفاصيل الفاتورة",
  AR_TOTALS: "المجموع",
  AR_TOTALS_SUB: "المجموع النهائي",
  AR_ACCOUNT: "الحساب",
  AR_REFERENCE: "المرجع",
  AR_AGENT_NAME: "اسم العميل",
  AR_DATE: "التاريخ",
  AR_STORE: "المخزن",
  AR_BARCODE: "الباركود",
  AR_MATERIAL: "المادة",
  AR_UNIT: "الوحدة",
  AR_UNIT_PRICE: "سعر الوحدة",
  AR_QUANTITY: "الكمية",
  AR_ITEM_DISC: "خصم",
  AR_ITEM_ADD: "اضافة",
  AR_QUANTITY_PRICE: "سعر الكمية",
  AR_ADD: "اضافة",
  AR_DELETE: "حذف",
  AR_ADD_ITEM: "اضافة صنف",
  AR_INVOICE_DISC: "خصم",
  AR_INVOICE_ADD: "اضافة",
  AR_SUBTOTAL: "السعر الاجمالي",
  AR_SUBMIT: "ارسال",
  AR_DISC_VALUE: "قيمة الخصم",
  AR_DISC_PERCENT: "المئوية",
  AR_ADD_VALUE: "قيمة الاضافة",
  AR_ADD_PERCENT: "المئوية",
  AR_TRANSFER: "نقل",
  AR_PRAINT: "طباعة",


  // EN - MISC //
  EN_HIT_SEARCH: 'Hit the search icon and seach for users!',
  EN_NO_USERS_CATEGORY: 'No users found with this category!',
  EN_CALL: "Call",
  EN_CANCEL: "Cancel",
  EN_CONFIRM_CALL_TITLE: "Call this number?",
  EN_CONFIRM_CALL_SUBTITLE: "Your carrier may charge you for this call!",

  // AR - MISC //
  AR_HIT_SEARCH : 'اضغط على زر البحث',
  AR_NO_USERS_CATEGORY : 'لا يوجد مشتركون تحت هذا التصنيف',
  AR_CALL: "اتصال",
  AR_CANCEL: "إلغاء",
  AR_CONFIRM_CALL_TITLE: "الاتصال بهذا الرقم؟",
  AR_CONFIRM_CALL_SUBTITLE: "شركة الاتصالات قد تخصم من رصيدك",

  // EN - Errors - Warnings - Alerts - Toast //
  EN_BTN_DISMISS: "Dismiss",
  EN_NO_REGION_TITLE: "You have no regions!",
  EN_NO_REGION_SUBTITLE: "Kindly contact your administrator to add regions and nodes for you.",
  EN_ERROR_TITLE: "Error",
  EN_ERROR_SUBTITLE: "Something went wrong!",
  EN_NO_WHATSAPP_NUMBER_TITLE: "WhatsApp number NOT found!",
  EN_NO_WHATSAPP_NUMBER_SUBTITLE: "Please update their number, then try again!",
  EN_SYNC_CONFRIM: "Sync",
  EN_SYNC_TITLE: "Do you want to sync your data with the server?",
  EN_SYNC_SUBTITLE: "Last sync was on: ",
  EN_SYNC_NEW_SUBTITLE: "This is your <b>first</b> sync.",
  EN_SYNC_SUCCESSF: "Synced successfully!",
  EN_NO_USER_FOUND_BARCODE: "No user found with this barcode.",

  // AR - Errors  - Warnings - Alerts - Toast //
  AR_BTN_DISMISS: "إغلاق",
  AR_NO_REGION_TITLE: "لا يوجد لديك مناطق",
  AR_NO_REGION_SUBTITLE: "لطفاً، تواصل مع اﻹدارة ﻹضافة المناطق لديك.",
  AR_ERROR_TITLE: "خطأ فني",
  AR_ERROR_SUBTITLE: "حصل خطأ ما!",
  AR_NO_WHATSAPP_NUMBER_TITLE: "لا يوجد رقم واتساب",
  AR_NO_WHATSAPP_NUMBER_SUBTITLE: "يرجى تحديث بيانات المشترك أولاً",
  AR_SYNC_CONFRIM: "مزامنة",
  AR_SYNC_TITLE: "هل تريد مزامنة بياناتك؟",
  AR_SYNC_SUBTITLE: "آخر مزامنة كانت في: ",
  AR_SYNC_NEW_SUBTITLE: "هذه <b>المزامنة</b> اﻷولى لك",
  AR_SYNC_SUCCESSF: "تمت المزامنة بنجاح!",
  AR_NO_USER_FOUND_BARCODE: "لم يتم العثور على مستخدم بهذا الباركود",
}

// export const DEF = {
//   // EN_: ,
//   // EN - POPOVER LIST //
//   EN_RECEIPT: "Receipt / Deposit",
//   EN_REFUND: "Debit / Withdraw",
//   EN_TICKET: "Ticket",
//   EN_FINANCIAL: "Financial Management",
//   EN_SERVICE: "Service",
//   EN_STATMENT_OF_ACCOUNT: "Statement of Account",
//   EN_DISCONNECT: "Disconnect",
//   EN_PING: "Ping",
//   EN_CLEAR_MAC: "Clear MAC",
//   EN_CHANGE_SERVICE: "Change Service",
//   EN_RECHARGE: "Recharge",
//   EN_END_SESSION: "End Session",
//   EN_ADD_TO_ARCHIVE: "Add to Archive List",
//   EN_EXTRA_GIGA: "Extra Giga",
//   EN_CONSUMPTION: "Consumption",
//   EN_DIRECTIONS: "Directions",
//   EN_DETAILS: "Details",
//   EN_VISIT: "Visit",
//   EN_REMINDER: "Remind Me Later",
//   EN_SHOW_NEIGHBORS: "Show Neighbors",
//   EN_WHATSAPP: "WhatsApp",
//   EN_INFECT: "Infect",
//   EN_SERVICES: "Services",

//   // EN - DETAILS + MANAGE//
//   EN_NAME: "Name",
//   EN_USERNAME: "Username",
//   EN_PASSWORD: "Password",
//   EN_LOGIG_PASSWORD: "App Password",
//   EN_NODE: "Node",
//   EN_ADDRESS: "Address",
//   EN_MOBILE: "Mobile",
//   EN_EMAIL: "Email",
//   EN_PHONE: "Phone",
//   EN_NATIONALITY: "Nationality",
//   EN_WHATSAPP_MOBILE: "WhatsApp Mobile",
//   EN_SERVICE_TYPE: "Service Type",
//   EN_LAST_LOGIN: "Last Login",
//   EN_LAST_LOGOUT: "Last Logout",
//   EN_MAC_ADDRESS: "MAC Address",
//   EN_ROUTER_MODEL: "Router Model",
//   EN_CATEGORY: "Category",
//   EN_COLLECTOR: "Collector",
//   EN_FRAMED_IP: "Framed IP",
//   EN_EXPIRY_DATE: "Expiry Date",
//   EN_BALANCE: "Balance",
//   EN_SPEED: "Speed",
//   EN_AUTO_RECHARGE: "Auto Recharge",
//   EN_FALLBACK: "Fallback",
//   EN_DISCOUNT: "Discount",

//   // EN - MAIN VIEW + MENU //
//   EN_ONLINE: "Online",
//   EN_OFFLINE: "Offline",
//   EN_ENABLE: "Enable",
//   EN_ENABLED: "Enabled",
//   EN_DISABLE: "Disable",
//   EN_DISABLED: "Disabled",
//   EN_LOCKED: "LOCKED",
//   EN_TERMINATE: "Terminate",
//   EN_EDIT: "Edit",
//   EN_SUBSCRIBER_LIST: "Subscriber List",
//   EN_MY_SERVICES: "My Service",
//   EN_VIEW_BY_CATEGORY: "View By Category",
//   EN_TOTAL: "Total",
//   EN_INFECTED: "Infected",
//   EN_ARCHIVED: "Archived",
//   EN_ACTIVE: "Active",
//   EN_SUSPENDED: "Suspended",
//   EN_EXPIRED: "Expired",
//   EN_REGIONS: "Regions",
//   EN_GLOBAL_SEARCH: "Global Search",
//   EN_ROUTE: "Route",
//   EN_OVER_CREDIT_LIMIT: "Over Credit Limit",
//   EN_NEED_RECHAREG: "Need Recharge",
//   EN_NO_REGISTERED_DATE: "No registered date",


//   // EN - LOGIN //
//   EN_CHOOSE_ACCOUNT:  "Choose account",
//   EN_ADD_ACCOUNT:  "Add Account",
//   EN_VERSION: "v",

//   // AR - LOGIN //
//   AR_CHOOSE_ACCOUNT:  "اختر حساباً",
//   AR_ADD_ACCOUNT:  "أضف حساباً",
//   AR_VERSION: "الإصدار",

// }